-- High-confidence security telemetry for manual review. Routine validation
-- failures and ordinary button spam are intentionally not written here.
CREATE TABLE IF NOT EXISTS public.security_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id text,
  ip_address text,
  event_type text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  route text,
  user_agent text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS security_events_created_idx
  ON public.security_events (created_at DESC);
CREATE INDEX IF NOT EXISTS security_events_profile_created_idx
  ON public.security_events (profile_id, created_at DESC)
  WHERE profile_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS security_events_ip_created_idx
  ON public.security_events (ip_address, created_at DESC)
  WHERE ip_address IS NOT NULL;

ALTER TABLE public.security_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.security_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON public.security_events TO service_role;

-- Defense in depth: browser Supabase keys can read the public lobby/catalog
-- tables they need, but cannot mutate wallet or game settlement state even if
-- an older permissive RLS policy still exists in an installation.
REVOKE ALL ON public.user_profiles FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.inventory_items FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.coinflip_games FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.case_openings FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.roll_rounds FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.roll_bets FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.case_battle_games FROM anon, authenticated;
REVOKE ALL ON public.mines_fairness_states FROM anon, authenticated;
REVOKE ALL ON public.case_fairness_states FROM anon, authenticated;
REVOKE ALL ON public.upgrader_games FROM anon, authenticated;
REVOKE ALL ON public.upgrader_fairness_states FROM anon, authenticated;
REVOKE ALL ON public.case_battle_fairness_secrets FROM anon, authenticated;
REVOKE ALL ON public.live_casino_sessions FROM anon, authenticated;
REVOKE ALL ON public.live_casino_rounds FROM anon, authenticated;
REVOKE ALL ON public.live_casino_transactions FROM anon, authenticated;
